/*
 * RESTful API ToDoList App
 *
 * mencoba membuat RESTful API untuk aplikasi ToDoList
 *
 * API version: 1.0
 * Contact: hafiz@mail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Showtodolist struct {
	// todolist id
	Id string `json:"id,omitempty"`
	// todolist name
	Name string `json:"name,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
