/*
 * RESTful API ToDoList App
 *
 * mencoba membuat RESTful API untuk aplikasi ToDoList
 *
 * API version: 1.0
 * Contact: hafiz@mail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Success bool `json:"success,omitempty"`
}
